# Blog info
blog_name: EyreFree
slogan: Not all those who wander are lost.
url: http://www.eyrefree.org

# Set avatar (Absolute url and relative url)
avatar: https://dn-coding-net-production-static.qbox.me/3f0503a5-2696-44e1-98dd-d755a07c6c2d.jpg?imageMogr2/auto-orient/format/jpeg/crop/!549x549a0a0

# Set favicon
favicon: /favicon.ico

# For seo
keywords: EyreFree,C/C++,Objective-C,Swift,iOS,OS X

home_nav:
  - name: 博客
    url: /archives
    target: _blank
  #- name: 简历
  #  url: http://resume.eyrefree.org/
  #  target: _blank
  - name: 简书
    url: http://www.jianshu.com/users/e4d1f69048ea
    target: _blank
  - name: Coding
    url: https://coding.net/u/eyrefree
    target: _blank
  - name: GitHub
    url: http://github.com/eyrefree
    target: _blank
  #- name: LinkedIn
  #  url: http://www.linkedin.com/in/eyrefree
  #  target: _blank
  - name: V2EX
    url: http://v2ex.com/member/eyrefree
    target: _blank
  - name: CSDN
    url: http://my.csdn.net/EyreFree
    target: _blank
  - name: Steam
    url: http://steamcommunity.com/id/EyreFree
    target: _blank
  - name: Battle.net
    url: http://d3.blizzard.cn/profile/EyreFree-5717/478027
    target: _blank

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 项目
    url: /project/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以发邮件给我 eyrefree@eyrefree.org

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style
personal_style: /css/eyrefree.css

home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
#google_analytics: UA-74357398-1
baidu_analytics: 638f7245dab1e13e3d8fbdd9cc3b0895

# Comment service
#disqus_shortname: eyrefree
duoshuo_shortname: eyrefree


# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "1993, Boy, ECIT."
    - "并非所有流浪者都迷失了自我."
    - "iOSer, C / C++ / Objective-C / Swift."
  - type: qq
    icon: icon-qq
    text_key: QQ
    text_value: "1795179491"
    text_value_url: http://wpa.qq.com/msgrd?v=3&uin=1795179491&site=qq&menu=yes
  - type: wechat
    icon: icon-wechat
    text_key: 微信
    text_value: "EyreFreePro"
    text_value_url: http://bedroom.eyrefree.org/images/eyrefreepro.png
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "EyreFree"
    text_value_url: http://weibo.com/eyrefree777
  - type: twitter
    icon: icon-twitter
    text_key: 推特
    text_value: "EyreFree777"
    text_value_url: https://twitter.com/EyreFree777
  - type: mail
    icon: icon-mail
    text_key: 邮箱
    text_value: "eyrefree@eyrefree.org"
    text_value_url: mailto:eyrefree@eyrefree.org
  - type: location
    icon: icon-location
    text_key: 位置
    text_value: "上海"
    text_value_url: "http://map.baidu.com/?newmap=1&ie=utf-8&s=s%26wd%3D%E4%B8%8A%E6%B5%B7"
  - type: info
    icon: icon-info
    text_key: 备案
    text_value: "苏ICP备15023694号"
    text_value_url: http://www.miitbeian.gov.cn/state/outPortal/loginPortal.action


link:
  - name: Breaker's Blog
    info: 作为意志和表象的世界
    url: http://blog.0x7c00.cn/
    avatar: https://dn-coding-net-production-static.qbox.me/b3981953-0dad-48c1-adab-be1b95359b1a.jpg?imageMogr2/auto-orient/format/jpeg/crop/!220x220a0a0
  - name: Vincent Yao
    info: 全干工程师
    url: http://blog.ookcode.com/
    avatar: https://dn-coding-net-production-static.qbox.me/17f4a530-afa3-435f-af71-42ada41d1b66.png?imageMogr2/auto-orient/format/png/crop/!248x248a0a0
  - name: TimothyQiu's Blog
    info: Hi, this is Timothy Qiu. I'm a new programmer.
    url: http://timothyqiu.com/
    avatar: https://dn-coding-net-production-static.qbox.me/2212a32f00cca72b5561aef00ebb5dc7.png
  - name: 沉没大陆
    info: Daterlove
    url: http://www.sinkland.cn/
    avatar: https://avatars0.githubusercontent.com/u/11631445?v=3&s=460
  - name: Geek情怀
    info: 有什么用呢？因为它看起来很美...
    url: https://segmentfault.com/blog/wzhvictor
    avatar: https://sfault-avatar.b0.upaiyun.com/510/717/510717055-563941d905997_huge256
  - name: 小飞侠
    info: 爱生活，爱Coding， 幸福快乐的小飞侠
    url: http://www.flypie.cn/
    avatar: https://avatars3.githubusercontent.com/u/12812523?v=3&s=460
  - name: 江小湖Laker
    info: 进击的程序媛
    url: http://laker.me/blog/
    avatar: https://dn-coding-net-production-static.qbox.me/80ab1c83-5194-4850-94bd-cb42c4bbafc8.png?imageMogr2/auto-orient/format/png/crop/!497x497a0a2
  - name: 佳佳酱
    info: 跨次元日常卖萌
    url: https://luojia.me/
    avatar: https://dn-coding-net-production-static.qbox.me/15b151ef-2df1-457a-913f-ec62d7b536fd.jpg?imageMogr2/auto-orient/format/jpeg/crop/!800x800a0a0
  - name: Airing
    info: 我是一只小小小小熊
    url: http://ursb.me/
    avatar: https://dn-coding-net-production-static.qbox.me/8cc80ba0-f0ad-4fe8-87f9-15e02ed64c65.jpg?imageMogr2/auto-orient/format/png/crop/!493x493a0a0
  - name: 无恙
    info: Xiekers Blog，博主小可。
    url: http://blog.xieke.org/
    avatar: https://dn-coding-net-production-static.qbox.me/94a6ef92-554f-4ac2-9316-9134c3a704fb.jpg
  - name: Jvaeyhcd's Note
    info: My Coding Note。
    url: http://www.jvaeyhcd.cc/
    avatar: https://dn-coding-net-production-static.qbox.me/0dcf6be4-e41e-4842-80af-af8f2b0eb3f3.jpg
  - name: 小栈
    info: 个人博客
    url: http://lancelot_lewis.coding.me/
    avatar: https://dn-coding-net-production-static.qbox.me/69ebe443-7644-4656-8d51-a5c8b8b78dd8.jpg?imageMogr2/auto-orient/format/jpeg/crop/!403x403a27a44
  - name: 海诺者
    info: PHP终极粉丝
    url: https://blog.hainuo.info/
    avatar: https://dn-coding-net-avatar.qbox.me/4cc88a4e-7adc-469f-98a5-6091ef2a35c3.jpg
  - name: 六阿哥博客
    info: 记录一个iOS程序员的成长历程
    url: https://blog.6ag.cn
    avatar: https://avatars0.githubusercontent.com/u/9330618?v=3&s=460
  - name: Gua Blog
    info: Innovation, in iOS development.
    url: http://desgard.com/
    avatar: https://avatars3.githubusercontent.com/u/7804535?v=3&s=460
  - name: iOS Developer
    info: 学会生活、懂得分享。做好自己、快乐你我他！
    url: http://www.ch8888.cn/
    avatar: https://avatars0.githubusercontent.com/u/5237197?v=3&s=460
  - name: Swift迷
    info: 致力于打造一个国内专业的Apple Swift交流和分享地方
    url: http://www.swiftmi.com/
    avatar: https://avatars0.githubusercontent.com/u/3375497?v=3&s=460

project:
  - type: personal
    name: TencentLinkupPlugin
    url: https://github.com/EyreFree/TencentLinkupPlugin
    intro: 腾讯游戏大厅连连看辅助
  - type: personal
    name: mspaint
    url: https://github.com/EyreFree/mspaint
    intro: C# 高仿 Windows 画图板
  - type: personal
    name: Gobang
    url: https://github.com/EyreFree/Gobang
    intro: Cocos2d-x 人机对战五子棋游戏
#  - type: personal
#    name: beside
#    url: https://github.com/forsigner/beside
#    intro: I need you beside me
#  - type: personal
#    name: web-fontmin
#    url: https://github.com/forsigner/web-fontmin
#    intro: 字体子集化，在线提取你需要的字体
#  - type: personal
#    name: magic-check
#     url: https://github.com/forsigner/magic-check
#     intro: Beautify Radio and Checkbox with pure CSS
#   - type: personal
#     name: nice-bar
#     url: https://github.com/forsigner/nice-bar
#     intro: A nice and lightweight scrollbar
#   - type: personal
#     name: angular-nice-bar
#     url: https://github.com/forsigner/angular-nice-bar
#     intro: A nice and lightweight scrollbar in Angular
#   - type: personal
#     name: fo-popover
#     url: https://github.com/forsigner/fo-popover
#     intro: A nice popover for Angular
#   - type: personal
#     name: fo-tooltip
#     url: A nice tooltip for Angular
#     intro: https://github.com/forsigner/fo-tooltip
#   - type: personal
#     name: fo-modal
#     url: https://github.com/forsigner/fo-modal
#     intro: A nice modal for Angular
#   - type: personal
#     name: mocer
#     url: https://github.com/forsigner/mocer
#     intro: Setup a mock server easily
#   - type: personal
#     name: node-pngdefry
#     url: https://github.com/forsigner/node-pngdefry
#     intro: Repairing iPhone fried PNGs using Node.js
#   - type: personal
#     name: ng-simditor
#     url: https://github.com/forsigner/ng-simditor
#     intro: Angular directive for simditor
